### ISSUE TITLE
Keyword is out of sync with earthly.vim 

### ISSUE THREAD

**Issue by wingyplus** [earthly/earthly-emacs#20]
From a quick look at https://github.com/earthly/earthly.vim/blob/main/syntax/Earthfile.vim#L50. I see some of the keyword is missing:

* `DOCKER LOAD`
* `DOCKER PULL`
* `CACHE`

**Comment by wingyplus** [comment]
@vladaionescu I didn't see any reference from https://docs.earthly.dev/docs/earthfile documentation. I found some of them only at https://github.com/earthly/earthly/blob/main/ast/parser/EarthLexer.g4. Can you help me clarify those syntaxes?

**Comment by vladaionescu** [comment]
Hi @wingyplus - `DOCKER LOAD` and `DOCKER PULL` are obsolete for quite a while now, so we don't need to add them.

`CACHE` is a new command, that hasn't been GA'd just yet. See details here: https://github.com/earthly/earthly/issues/1399

**Comment by wingyplus** [comment]
@vladaionescu Thank you for your information.  Adding only `CACHE` would solve the issue.
